Updated git ignore
Visual-Testing-for-Android-Apps/web pull request #10
Opened 2021-04-15 05:13 UTC by mt-empty

Git ignore for the following:
* linux
* windows
* macos/osx
* node
* react

2021-04-16 00:06 UTC, idomo1 requested changes

2021-04-16 00:06 UTC, idomo1 commented on .gitignore
> -!/dist/.gitkeep
Please add these bottom two lines back

2021-04-17 01:54 UTC, mt-empty commented on .gitignore
> -!/dist/.gitkeep
should be resolved now

2021-04-17 02:32 UTC, idomo1 approved these changes

2021-04-17 03:16 UTC, merged