Feature/damien/enhanced video results
Visual-Testing-for-Android-Apps/web pull request #37
Opened 2021-08-24 09:15 UTC by idomo1

## Proposed changes

Enhance the video results by proving explanations and linking out to Material Design resources.

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] DevOps related

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [project guidelines](https://github.com/Visual-Testing-for-Android-Apps/Project-guidelines) doc
- [x] I locally linted my code
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

https://user-images.githubusercontent.com/53201250/130590371-b52e4e6c-60d8-45cc-8aeb-a54ecf97a5e6.mov

<img width="409" alt="Screen Shot 2021-08-24 at 7 11 00 pm" src="https://user-images.githubusercontent.com/53201250/130590464-e981d114-0495-431f-a28c-5a4a0c378536.png">
<img width="1195" alt="Screen Shot 2021-08-24 at 7 11 21 pm" src="https://user-images.githubusercontent.com/53201250/130590473-d157720c-c9c0-4d6e-8555-e40f72d8340d.png">

2021-08-24 09:15 UTC, idomo1 commented
I branched this off of the colour scheme picker branch, so wait for that one to be merged before reviewing this.

2021-08-25 09:16 UTC, leanne-b reviewed
**Desktop View:**
- I like the description boxes and the fonts they look nice
- It would be nice if the video with error analysing video could be aligned with the other normal videos, right now it looks out of alignment because the description box isn't the same size as the other videos. Please align the videos in a column with their left edges lining up, similarly for the description boxes. 
- It might be help to have two columns to help align things with the video on the left and the descriptions in the right column or somehow make all the description boxes the same size so when they're centred the vids+descrip are all in alignment. 
![image](https://user-images.githubusercontent.com/81729265/130758337-5591f039-4640-43cb-ad97-a3385357772c.png)

- I think the description style can be more consistent, they look differently spread in the image below. 
![image](https://user-images.githubusercontent.com/81729265/130760746-bc9396ca-3ee8-43a6-a2ba-a11e958ed1d6.png)
- The flow layout is weird at zoom <=90%, full screen
![image](https://user-images.githubusercontent.com/81729265/130763023-bd19990b-afdd-4696-8002-8c7102311024.png)
- If the colour scheme selector is aligned left, then everything below should be aligned left for consistency

**Mobile View:**
- On Mobile it can be a little bit confusing to differentiate which feedback is for which video, I thought the "missing scrim" was for the video below because it looked like a heading but it was actually for the video above. 

![image](https://user-images.githubusercontent.com/81729265/130754121-39c13e9f-76a9-4f5b-b62e-351c22a9beec.png)

- I think it would be good to have a heading above each image or video in the font style similar to the "missing scrim". Or something visual to help differentiate between the files and the feedback that belongs to it. 
- Move the description above the video instead? 

**Tablet view:**
- images section of the report gives an empty feel because there is a lot of space on both sides and small short text
![image](https://user-images.githubusercontent.com/81729265/130756662-191e9dd4-8ba0-4733-bd1c-3952820ec47d.png)

- Video section: if you keep the media centred, I think you need padding/margins on the left+right of description part for missing scrim so it doesn't spread out towards the edges so much
![image](https://user-images.githubusercontent.com/81729265/130755851-80b83a5a-8789-4b4c-ab61-fd37928e6e72.png)

2021-08-25 12:28 UTC, mt-empty commented
Yea images and videos are not consistent, becuase of the image result limitation, but I was thinking maybe we could isolate image from video results, that way its more consistent, e.g. rows spesific for images and rows specific for videos 

This is how it looks like on my desktop
![image](https://user-images.githubusercontent.com/59728838/130790470-314e23af-06a8-4c33-bc80-fc29c4e7e19f.png)

2021-08-25 12:34 UTC, mt-empty requested changes
This is better than mine, I left some comments.

2021-08-25 12:34 UTC, mt-empty commented on src/components/reportPage/results-page.css
> +    max-width: 30rem;
Why is there two of `video-result-explanation` and `video-result-container` in this file?

2021-08-28 02:16 UTC, idomo1 commented on src/components/reportPage/ImageResult.jsx
> +          </div>
You've already done it on your branch I think so I'll leave it

2021-08-28 02:56 UTC, Akshith-Patil approved these changes
Looks good!

2021-08-28 02:56 UTC, mt-empty approved these changes

2021-08-28 03:21 UTC, merged