Feature/filter results
Visual-Testing-for-Android-Apps/web pull request #48
Opened 2021-09-10 12:37 UTC by Akshith-Patil

## Proposed changes

- Added a dropdown filter menu for reportPage
- Allows you to filter results by defect type (Both image and video defects)

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] DevOps related

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [project guidelines](https://github.com/Visual-Testing-for-Android-Apps/Project-guidelines) doc
- [x] I locally linted my code
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

Before interacting with filter menu:
![Before Filter](https://user-images.githubusercontent.com/81655881/132854040-964ad884-e831-42bd-9483-61afa156ee03.PNG)

After selecting options from filter menu:
![After 1 Filter](https://user-images.githubusercontent.com/81655881/132854139-99de4284-0a22-4652-a473-2d63f2ae71bc.PNG)
![After 2 Filter](https://user-images.githubusercontent.com/81655881/132854157-f80c457f-4180-4ad4-84dd-8f5114e72c8a.PNG)

During the selection
![During Filter](https://user-images.githubusercontent.com/81655881/132854193-fbbfce97-258e-48d7-a731-3491caf22bc4.PNG)

2021-09-11 01:30 UTC, idomo1 requested changes
Nice work guys 👍 
Mostly just some minor things that could be improved.

It's a bit misleading where the defect filter is placed. It's under the image results section, but it's applying to both
![image](https://user-images.githubusercontent.com/53201250/132931904-a99f3552-67b6-4475-99f2-d9f31bf75d1f.png)

2021-09-11 01:30 UTC, idomo1 commented on src/components/reportPage/ReportPage.jsx
> +  ];
Could you order the video defects by the value please? And seperate the image and video defects, something like this:
```
const videoDefects = [
{ value: "1", label: "No defect" },
{ value: "2", label: "Missing scrim" },
...
];

const imageDefects = [
{ value: "Component occlusion", label: "Component Occlusion" },
...
];

const allDefects = [...videoDefects, ...imageDefects];
```

2021-09-11 01:30 UTC, idomo1 commented on src/components/reportPage/ReportPage.jsx
> +import { alignPropType } from "react-bootstrap/esm/DropdownMenu";
Unused import

2021-09-11 01:30 UTC, idomo1 commented on src/components/reportPage/ReportPage.jsx
> +  vidFilterRef.current = videoFilterType;
I can't see these being used anywhere

2021-09-11 01:30 UTC, idomo1 commented on src/components/reportPage/ReportPage.jsx
> +  const [videoFilterType, setVideoFilterType] = useState("0");
Can't see these being used anywhere

2021-09-11 01:30 UTC, idomo1 commented on src/components/reportPage/ReportPage.jsx
> +  const [displayValue, getValue] = useState([]);
Could we think of a better name for this? It's not very clear what this list is. Also should be `set` not `get`.

2021-09-11 01:30 UTC, idomo1 commented on src/components/reportPage/ReportPage.jsx
> +    }
Could be shortened to `return displayValue.length === 0 ||
      (displayValue.includes("1") && imageResult["bug_type"].length === 0) ||
      found`

2021-09-11 01:30 UTC, idomo1 commented on src/components/reportPage/ReportPage.jsx
> +  };
Could be shortened to `return displayValue.length === 0 || found`

2021-09-11 01:30 UTC, idomo1 commented on src/components/reportPage/ReportPage.jsx
> +      (displayValue.includes("1") && imageResult["bug_type"].length === 0) ||
Maybe define "1" as a constant to give it meaning? `const IMAGE_NO_DEFECT_VALUE = "1";`
`displayValue.includes(IMAGE_NO_DEFECT_VALUE)`

2021-09-11 01:35 UTC, idomo1 commented on src/components/reportPage/ReportPage.jsx
> +  ];
Just noticed, "1" is being used as no defects for images. There is a "1" for video results though which is missing. Ig you have a look at Repository.js there is a mapping for the video results
![image](https://user-images.githubusercontent.com/53201250/132931976-706d2662-8a49-4b2a-a508-5426f0009e9e.png)

2021-09-11 12:07 UTC, Akshith-Patil commented
Hey @idomo1 Damien, thanks for the feedback, made all changes mentioned above. Had a question regarding the 'classification', if no defect is found, is the 'classification' tag just empty?

2021-09-12 03:46 UTC, idomo1 commented
@Akshith-Patil From what I understand, for video results "Can't place in space" = No defect. Classification will always be one of the 10 options

2021-09-13 07:49 UTC, idomo1 approved these changes
Just a typo to fix if you can be bothered, no biggy

2021-09-13 07:49 UTC, idomo1 commented on src/components/reportPage/ReportPage.jsx
> +  const [selectedVideoDefects, setVideoFefects] = useState([]);
Typo, "setVideoDefects"

2021-09-13 09:55 UTC, merged