Feature/ak/batch job filelist
Visual-Testing-for-Android-Apps/web pull request #75
Opened 2021-10-10 10:07 UTC by Akshith-Patil

## Proposed changes

Created new file management design for upload section
1. Added 'search' bar for upload section
2. New 'remove all' button to delete all uploaded files
3. Thumbnails for image and video files
4. Pagination for Batch Job upload section
5. Modal popup to view files in full-sized view

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] DevOps related

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have read the [project guidelines](https://github.com/Visual-Testing-for-Android-Apps/Project-guidelines) doc
- [x] I locally linted my code
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

**Before Uploading Files**
![Before Upload](https://user-images.githubusercontent.com/81655881/136691167-792ceeea-e44f-49c1-bb8b-a951b1716900.PNG)

**After Uploading files**
![After Upload](https://user-images.githubusercontent.com/81655881/136691188-0716398a-7c3c-4420-af8f-3f4518a8b2b4.PNG)

After clicking on the file thumbnail
![Modal Popup](https://user-images.githubusercontent.com/81655881/136691214-b9862784-4682-4baf-9d6d-fbc8b3c75fea.PNG)

2021-10-10 12:56 UTC, mt-empty commented on src/components/reportPage/upload.css
> +  .modalContent {
should not be Camel case

2021-10-10 23:59 UTC, Akshith-Patil commented
> This fails to build, can you investigate?



> This fails to build, can you investigate?
There was an issue with the paginate package, but it has been fixed now

2021-10-11 01:08 UTC, mt-empty commented on src/components/reportPage/UploadBox.jsx
> +  const maxFiles = props.fileLimit == Infinity ? 0 : props.fileLimit;
This is Ok, but I would rather have an upper limit, having `Infinity` might break the website in ways we do not anticipate.

2021-10-11 01:29 UTC, idomo1 requested changes
Since you reverted merging in develop, if this PR is merged it will undo a bunch of work (have a look at the diff).
You might need to revert the revert commit

2021-10-12 03:31 UTC, closed without merging