Feature/ak/batch job filelist 2
Visual-Testing-for-Android-Apps/web pull request #77
Opened 2021-10-12 03:35 UTC by Akshith-Patil

## Proposed changes

Had issues with the previous branch, hence created a new branch before the revert commit. 

Created new file management design for upload section
1. Added 'search' bar for upload section
2. New 'remove all' button to delete all uploaded files
3. Thumbnails for image and video files
4. Pagination for Batch Job upload section
5. Modal popup to view files in full-sized view

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] DevOps related

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have read the [project guidelines](https://github.com/Visual-Testing-for-Android-Apps/Project-guidelines) doc
- [x] I locally linted my code
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

After uploading
![After Upload](https://user-images.githubusercontent.com/81655881/136886951-16c6c614-b928-462f-88d5-1bfa2bb57ff5.PNG)

Clicking on the file thumbnail
![Modal Popup](https://user-images.githubusercontent.com/81655881/136887000-d1f89e9d-fc59-464b-a923-96a2820e89d5.PNG)

2021-10-12 04:23 UTC, mt-empty requested changes
When you get the error message `Something went wrong`, the local files are no longer available for viewing  

![image](https://user-images.githubusercontent.com/59728838/136890964-0901dd18-e963-489a-b016-0c60c06ffb17.png)

Don't fix it if it takes too long.

2021-10-12 04:34 UTC, Akshith-Patil commented
> When you get the error message `Something went wrong, the local files are no longer available for viewing

That's strange, how did you get the `Something went wrong` error in the first place?

2021-10-13 10:19 UTC, mt-empty approved these changes

2021-10-15 01:47 UTC, idomo1 commented
If I have 2 pages of files, and remove all the files from the second page, I will be left with an empty list until I select page 1
![image](https://user-images.githubusercontent.com/53201250/137419209-1d000c77-307b-4cdc-86c6-5714ba7c758d.png)

2021-10-15 01:49 UTC, idomo1 commented
Is it an easy thing to add the controls to the bottom as well?

2021-10-15 01:51 UTC, idomo1 commented on src/components/reportPage/UploadSection.jsx
> +    var file_index = file;
Should be `const` and should be in camelCase (`fileIndex`)

2021-10-15 02:01 UTC, idomo1 approved these changes

2021-10-16 06:12 UTC, merged