commit about us page
Visual-Testing-for-Android-Apps/web pull request #91
Opened 2021-10-20 08:39 UTC by ZacWhittaker

This commit includes the about us page with contact information included

## Proposed changes

About us page added to the footer

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] DevOps related

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [project guidelines](https://github.com/Visual-Testing-for-Android-Apps/Project-guidelines) doc
- [x] I locally linted my code
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [x] Any dependent changes have been merged and published in downstream modules

## Further comments
n/a

2021-10-22 07:56 UTC, idomo1 requested changes
Looks good 👍

2021-10-22 07:56 UTC, idomo1 commented on src/components/mainPage/about-us-page.css
> +}
Should be using relative units (i.e `rem`) instead of fixed units (`pt`)

2021-10-22 07:56 UTC, idomo1 commented on src/components/mainPage/AboutUsPage.jsx
> +          <span className="c2">
It doesn't look like these classes are defined anywhere (`c2`, `c5`, `c10`, `c7`). Could you remove them if that's the case? If they are being used then they could use better names

2021-10-23 06:39 UTC, zascii commented on src/components/mainPage/about-us-page.css
> +}
I don't think there is a relative unit for font weight

2021-10-23 06:40 UTC, zascii commented on src/components/mainPage/AboutUsPage.jsx
> +          <span className="c2">
Stealing these from the privacy policy page

2021-10-23 06:41 UTC, idomo1 commented on src/components/mainPage/about-us-page.css
> +}
Font weight is fine, all the others I mean where `pt` is used

2021-10-24 08:39 UTC, zascii commented on src/components/mainPage/about-us-page.css
> +}
Done

2021-10-24 08:46 UTC, mt-empty commented on src/components/mainPage/AboutUsPage.jsx
> +          <span className="c2">
class names where generated by google doc

2021-10-24 08:51 UTC, mt-empty requested changes
All good, except that one unused class

2021-10-24 08:51 UTC, mt-empty commented on src/components/mainPage/about-us-page.css
> +.text-p {
This is not used

2021-10-24 08:56 UTC, idomo1 approved these changes
Nice work 👍 
Just need to fix that css linting failure

2021-10-24 09:14 UTC, zascii commented on src/components/mainPage/about-us-page.css
> +.text-p {
fixed

2021-10-24 09:26 UTC, closed without merging